### ISSUE TITLE
A `$ref` is not allowed directly under `path`

### ISSUE THREAD

**Issue by wtjones** [dgarcia360/openapi-boilerplate#2]
Per https://swagger.io/docs/specification/using-ref/, this is invalid:

```
paths:
  $ref: "./paths/_index.yaml"
```
You can do this however:

```
paths:
  /pets:
    $ref: "./paths/listPets.yaml"
```

listPets.yaml (added the get node)
```
get:
  summary: List all pets
  operationId: listPets
  tags:
    - pets
  parameters:
```
